### ISSUE TITLE
Add AAKR to anaconda?

### ISSUE THREAD

**Issue by rinelson456** [jmyrberg/aakr#2]
Hi,

I was wondering if you could add this to anaconda? Just so we can install it with our program that is dependent on CONDA.

Thank you!

**Comment by jmyrberg** [comment]
Hi! I think the easiest way would be to install pip in the conda environment, and then to use pip to install the package itself. You can see more information on how to do this [here](https://stackoverflow.com/questions/41060382/using-pip-to-install-packages-to-anaconda-environment).

**Comment by rinelson456** [comment]
So we did try that but it still didn't work with our program.
